<a href="https://colab.research.google.com/github/Sharonsellnorbert/DSA_B13_casestudy/blob/main/case_study_Data_Acquisition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [12]:
po=pd.read_csv('/content/population.csv')

In [14]:
po.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [17]:
po.shape

(25, 2)

In [22]:
po.dtypes

country       object
population     int64
dtype: object

In [26]:
gd=pd.read_excel('/content/gdp.xlsx')

In [29]:
gd.columns

Index(['Country', 'GDP'], dtype='object')

In [30]:
gd.dtypes

Country    object
GDP         int64
dtype: object

In [31]:
iu=pd.read_json('/content/internet_users.json')

In [33]:
df= pd.DataFrame(iu)

In [34]:
df

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [35]:
x=pd.read_xml('/content/literacy_rate.xml')

In [36]:
dfx=pd.DataFrame(x)

In [37]:
dfx

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [38]:
# Explore Population dataset
print("POPULATION")
print("Rows and Columns:", po.shape)
print("Column Names:", po.columns)
print("Data Types:")
print(po.dtypes)
print("Missing Values:")
print(po.isnull().sum())
print("Duplicate Records:", po.duplicated().sum())


# Explore GDP dataset
print("\nGDP")
print("Rows and Columns:", gd.shape)
print("Column Names:", gd.columns)
print("Data Types:")
print(gd.dtypes)
print("Missing Values:")
print(gd.isnull().sum())
print("Duplicate Records:", gd.duplicated().sum())


# Explore Internet Users dataset
print("\nINTERNET USERS")
print("Rows and Columns:", df.shape)
print("Column Names:", df.columns)
print("Data Types:")
print(df.dtypes)
print("Missing Values:")
print(df.isnull().sum())
print("Duplicate Records:", df.duplicated().sum())


# Explore Literacy Rate dataset
print("\nLITERACY RATE")
print("Rows and Columns:", dfx.shape)
print("Column Names:", dfx.columns)
print("Data Types:")
print(dfx.dtypes)
print("Missing Values:")
print(dfx.isnull().sum())
print("Duplicate Records:", dfx.duplicated().sum())

POPULATION
Rows and Columns: (25, 2)
Column Names: Index(['country', 'population'], dtype='object')
Data Types:
country       object
population     int64
dtype: object
Missing Values:
country       0
population    0
dtype: int64
Duplicate Records: 0

GDP
Rows and Columns: (25, 2)
Column Names: Index(['Country', 'GDP'], dtype='object')
Data Types:
Country    object
GDP         int64
dtype: object
Missing Values:
Country    0
GDP        0
dtype: int64
Duplicate Records: 0

INTERNET USERS
Rows and Columns: (25, 2)
Column Names: Index(['country', 'internet_users'], dtype='object')
Data Types:
country           object
internet_users     int64
dtype: object
Missing Values:
country           0
internet_users    0
dtype: int64
Duplicate Records: 0

LITERACY RATE
Rows and Columns: (25, 2)
Column Names: Index(['name', 'literacy_rate'], dtype='object')
Data Types:
name              object
literacy_rate    float64
dtype: object
Missing Values:
name             0
literacy_rate    0
dtype: int64
Duplicate Records: 0

In [52]:
po.rename(columns={'country': 'country'})

gd.rename(columns={'Country': 'country'})

df.rename(columns={'country': 'country'})

dfx.rename(columns={'name': 'country'})

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [53]:
print(po.dtypes)
print(gd.dtypes)
print(df.dtypes)
print(dfx.dtypes)

country       object
population     int64
dtype: object
country    object
GDP         int64
dtype: object
country           object
internet_users     int64
dtype: object
country           object
literacy_rate    float64
dtype: object

In [54]:
# Merge Population and GDP
merged = pd.merge(po, gd, on='country')

# Merge with Internet Users
merged = pd.merge(merged, df, on='country')

# Merge with Literacy Rate
merged = pd.merge(merged, dfx, on='country')


merged

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [58]:
merged['Internet_penetration']=(merged['internet_users']/merged['population']*100).round(2)
merged['GDP Per Capita']=(merged['GDP']/merged['population']).round(2)
merged

,country,population,GDP,internet_users,literacy_rate,Internet_penetration,GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

In [59]:
import sqlite3

conn = sqlite3.connect('/content/country_statistics.db')

merged.to_sql(
    'country_statistics',
    conn,
    if_exists='replace',
    index=False
)
print("Data successfully loaded into SQLite database.")

Data successfully loaded into SQLite database.

In [60]:
# Retrieve first 5 records
query = "SELECT * FROM country_statistics LIMIT 5;"

result = pd.read_sql_query(query, conn)

result

,country,population,GDP,internet_users,literacy_rate,Internet_penetration,GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [66]:
# 1. Top 5 countries by GDP
print(merged.sort_values('GDP', ascending=False).head(5))
print('---------------------------------------------------------')
# 2. Top 5 countries by population
print(merged.sort_values('population', ascending=False).head(5))
print('---------------------------------------------------------')
# 3. Average literacy rate
print(merged['literacy_rate'].mean())
print('---------------------------------------------------------')
# 4. Literacy rate greater than 90%
print(merged[merged['literacy_rate'] > 90])
print('---------------------------------------------------------')
# 5. Internet penetration greater than 70%
print(merged[merged['Internet_penetration'] > 70])
print('---------------------------------------------------------')
# 6. Top 5 GDP per capita
print(merged.sort_values('GDP Per Capita', ascending=False).head(5))
print('---------------------------------------------------------')
# 7. Total population
print(merged['population'].sum())
print('---------------------------------------------------------')
# 8. Average internet penetration
print(merged['Internet_penetration'].mean())

print('---------------------------------------------------------')
# 9. Country with highest internet users
print(merged.loc[
    merged['internet_users'].idxmax(),
    ['country', 'internet_users']
])
print('---------------------------------------------------------')
# 10. Correlation
print(merged['literacy_rate'].corr(
    merged['Internet_penetration']
))

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
4        Germany    83240525   4744000        79000000           99.0
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0

   Internet_penetration  GDP Per Capita
0                 94.26            0.09
1                 76.50            0.01
4                 94.91            0.06
2                 61.59            0.00
3                 93.77            0.03
---------------------------------------------------------
          country  population       GDP  internet_users  literacy_rate  \
1           China  1411778724  19230000      1080000000           97.2
2           India  1380004385   4187000       850000000           77.7
0   United States   331002651  30500000       312000000           99.0
15      Indonesia   273523615   1500000       212000000           96.0
10         Brazil   212559417   2330000       181000000           93.2

    Internet_penetration  GDP Per Capita
1                  76.50            0.01
2                  61.59            0.00
0                  94.26            0.09
15                 77.51            0.01
10                 85.15            0.01
---------------------------------------------------------
97.248
---------------------------------------------------------
           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet_penetration  GDP Per Capita
0                  94.26            0.09
1                  76.50            0.01
3                  93.77            0.03
4                  94.91            0.06
5                  97.22            0.06
6                  94.98            0.05
7                  92.62            0.04
8                  94.72            0.06
9                  93.43            0.07
10                 85.15            0.01
11                 85.65            0.02
12                 96.56            0.03
13                 94.11            0.04
14                 79.11            0.01
15                 77.51            0.01
16                 97.66            0.03
17                 81.81            0.02
18                 72.50            0.01
19                 90.72            0.01
20                 97.47            0.07
21                 98.21            0.11
22                 97.55            0.06
23                 97.76            0.11
24                 95.72            0.09
---------------------------------------------------------
           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet_penetration  GDP Per Capita
0                  94.26            0.09
1                  76.50            0.01
3                  93.77            0.03
4                  94.91            0.06
5                  97.22            0.06
6                  94.98            0.05
7                  92.62            0.04
8                  94.72            0.06
9                  93.43            0.07
10                 85.15            0.01
11                 85.65            0.02
12                 96.56            0.03
13                 94.11            0.04
14                 79.11            0.01
15                 77.51            0.01
16                 97.66            0.03
17                 81.81            0.02
18                 72.50            0.01
19                 90.72            0.01
20                 97.47            0.07
21                 98.21            0.11
22                 97.55            0.06
23                 97.76            0.11
24                 95.72            0.09
---------------------------------------------------------
          country  population       GDP  internet_users  literacy_rate  \
21    Switzerland     8654622    940000         8500000           99.0
23         Norway     5421241    580000         5300000          100.0
24      Singapore     5850342    530000         5600000           97.5
0   United States   331002651  30500000       312000000           99.0
9       Australia    25687041   1880000        24000000           99.0

    Internet_penetration  GDP Per Capita
21                 98.21            0.11
23                 97.76            0.11
24                 95.72            0.09
0                  94.26            0.09
9                  93.43            0.07
---------------------------------------------------------
4720039725
---------------------------------------------------------
89.6596
---------------------------------------------------------
country                China
internet_users    1080000000
Name: 1, dtype: object
---------------------------------------------------------
0.77279756813985