<a href="https://colab.research.google.com/github/Sharonsellnorbert/DSA_B13_casestudy/blob/main/NumPy_Pandas_Assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [18]:
#  Q1
arr=np.array([10,20,30,40,50])
print("Array",arr)
print("Shape of array",arr.shape)
print("Data type of array",arr.dtype)

Array [10 20 30 40 50]
Shape of array (5,)
Data type of array int64

In [10]:
# Q2
arr=np.array([5,10,15,20,25])
arr1=arr+5
arr2=arr*2
print("Original array:",arr)
print("\nAfter adding 5:",arr1)
print("\nAfter multipying with 2:",arr2)

Original array: [ 5 10 15 20 25]

After adding 5: [10 15 20 25 30]

After multipying with 2: [10 20 30 40 50]

In [14]:
# Q3
arr=np.array([12,15,18,20,25,30])
print("Mean",np.mean(arr))
print("Median",np.median(arr))
print("Minimum",np.min(arr))
print("Maximum",np.max(arr))
print("Standard Deviation",np.std(arr))

Mean 20.0
Median 19.0
Minimum 12
Maximum 30
Standard Deviation 6.027713773341708

In [36]:
# Q4
arr = np.array([10, 25, 30, 45, 50, 65, 70])
print("Values greater than 40 are")
print(arr[arr > 40])

Values greater than 40 are
[45 50 65 70]

In [20]:
import pandas as pd

In [28]:
# Q5
sdf=pd.DataFrame({
    'Name':['Anu','Rahul','Meera','Arun'],
    'Age':[21,22,20,23],
    'Score':[85,72,91,68]
})
print("Data Frame\n",sdf)
print('______________________________')
#

Data Frame
     Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68
______________________________

In [33]:
# Q6
print("Name and Score columns:")
display(sdf[['Name', 'Score']])
print('______________________')
print("Complete record of Meera:")
display(sdf[sdf['Name'] == 'Meera'])

Name and Score columns:

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

______________________
Complete record of Meera:

    Name  Age  Score
2  Meera   20     91

In [34]:
# Q7
print("Students with Score > 75:")
display(sdf[sdf['Score'] > 75])

Students with Score > 75:

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [35]:
# Q8
print("1. Number of rows and columns:")
print(sdf.shape)
print('______________________')

print("2. Column names:")
print(sdf.columns.tolist())
print('______________________')

print("3. Data types of columns:")
print(sdf.dtypes)
print('______________________')

print("4. Basic statistical summary:")
display(sdf.describe())

1. Number of rows and columns:
(4, 3)
______________________
2. Column names:
['Name', 'Age', 'Score']
______________________
3. Data types of columns:
Name     object
Age       int64
Score     int64
dtype: object
______________________
4. Basic statistical summary:

             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

In [40]:
# Q9
print("Original DataFrame:")
print(sdf)
print('______________________')
print("Sorted DataFrame:")
print(sdf.sort_values(by='Score', ascending=False))

Original DataFrame:
    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68
______________________
Sorted DataFrame:
    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

In [43]:
# Q10
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})

print("1. Identifying Missing Values:")
display(df.isnull())
print('______________________')

# Replace missing Age with mean age
df['Age'] = df['Age'].fillna(df['Age'].mean())
print("2. After replacing missing Age with mean:")
display(df)
print('______________________')

# Replace missing Score with mean score
df['Score'] = df['Score'].fillna(df['Score'].mean())
print("3. After replacing missing Score with mean:")
display(df)

1. Identifying Missing Values:

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

______________________
2. After replacing missing Age with mean:

  Name   Age  Score
0    A  21.0   80.0
1    B  22.0   75.0
2    C  23.0    NaN
3    D  22.0   90.0

______________________
3. After replacing missing Score with mean:

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

In [51]:
# Q11
# Load student_performance.csv into a Pandas DataFrame
student_df = pd.read_csv('/content/student_performance.csv')

print("1. First 5 records:")
display(student_df.head(5))
print('\n_________________________________\n')

print("2. Last 5 records:")
display(student_df.tail(5))
print('\n_________________________________\n')

print("3. Number of rows and columns:")
print(student_df.shape)
print('\n_________________________________\n')

print("4. Column names:")
print(student_df.columns.tolist())
print('\n_________________________________\n')

print("5. Data types:")
print(student_df.dtypes)
print('\n_________________________________\n')

print("6. Statistical summary of numerical columns:")
display(student_df.describe())

1. First 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

_________________________________

2. Last 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

_________________________________

3. Number of rows and columns:
(80, 11)

_________________________________

4. Column names:
['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Final_Score']

_________________________________

5. Data types:
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

_________________________________

6. Statistical summary of numerical columns:

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

In [53]:
# Q12

# 1. Filter students with Final_Score > 75
score_gt_75 = student_df[student_df['Final_Score'] > 75]
print("1. Students with Final Score > 75")
display(score_gt_75.head())
print('\n_________________________________\n')

# 2. Filter students with Attendance < 75
attendance_lt_75 = student_df[student_df['Attendance'] < 75]
print("2. Students with Attendance < 75%")
display(attendance_lt_75.head())
print('\n_________________________________\n')

# 3. Filter students in 'Data Science' department with Final_Score > 80
ds_gt_80 = student_df[(student_df['Department'] == 'Data Science') & (student_df['Final_Score'] > 80)]
print("3. Data Science students with Final Score > 80")
display(ds_gt_80.head())
print('\n_________________________________\n')

# 4. Sort the filtered 'Data Science' students by Final_Score in descending order
ds_sorted = student_df.sort_values(by='Final_Score', ascending=False)
print("4. Sorted Data Science students (Final Score ) in descending order:")
display(ds_sorted)

1. Students with Final Score > 75

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0

_________________________________

2. Students with Attendance < 75%

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0

_________________________________

3. Data Science students with Final Score > 80

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0

_________________________________

4. Sorted Data Science students (Final Score ) in descending order:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

In [46]:
# Q13: Feature Creation

# 1.
technical_cols = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
student_df['Average_Technical_Score'] = student_df[technical_cols].mean(axis=1)

# 2. Assign Performance based on Final_Score using a mapping function
def assign_performance(score):
    if score >= 90:
        return 'Outstanding'
    elif score >= 80:
        return 'Excellent'
    elif score >= 70:
        return 'Good'
    elif score >= 50:
        return 'Average'
    else:
        return 'Below Average'

student_df['Performance'] = student_df['Final_Score'].apply(assign_performance)

# Display the updated DataFrame (first 5 records showing newly added columns)
print("DataFrame with newly created 'Average_Technical_Score' and 'Performance' columns:")
display(student_df[['Name', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Average_Technical_Score', 'Final_Score', 'Performance']].head())

DataFrame with newly created 'Average_Technical_Score' and 'Performance' columns:

,Name,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Average_Technical_Score,Final_Score,Performance
0,Rahul Varma,89.4,86.3,81.9,76.7,83.575,82.7,Excellent
1,Kiran Pillai,70.3,63.1,65.1,62.3,65.200,60.3,Average
2,Fathima Joseph,79.9,80.4,65.3,68.0,73.400,67.1,Average
3,Rahul Sharma,65.8,50.7,52.6,48.8,54.475,57.2,Average
4,Asha Nair,90.1,82.9,72.4,87.7,83.275,81.9,Excellent

In [47]:
# Q14: GroupBy and Aggregation

# Group by Department and calculate count, mean, min, and max for Final_Score
dept_summary = student_df.groupby('Department')['Final_Score'].agg(['count', 'mean', 'min', 'max'])

# Rename columns for clarity
dept_summary = dept_summary.rename(columns={
    'count': 'Total_Students',
    'mean': 'Average_Final_Score',
    'min': 'Min_Final_Score',
    'max': 'Max_Final_Score'
})

print("Summary of Final Scores by Department:")
display(dept_summary)

Summary of Final Scores by Department:

,Total_Students,Average_Final_Score,Min_Final_Score,Max_Final_Score
Department,,,,
Data Science,1,55.100000,55.1,55.1
Commerce,8,67.825000,54.6,83.7
Computer Science,29,71.479310,40.6,96.0
Computer science,1,46.700000,46.7,46.7
Data Science,25,71.324000,43.5,97.0
Electronics,13,72.846154,51.2,86.9
data science,1,66.900000,66.9,66.9

In [65]:
# Q15
import numpy as np

# Convert column directly to a NumPy array
scores = student_df['Final_Score'].dropna().to_numpy()

# Calculate and print all required statistics
print("--- Final_Score Statistics ---")
print(f"Mean: {np.mean(scores):.2f}")
print(f"Median: {np.median(scores):.2f}")
print(f"Std Dev: {np.std(scores):.2f}")
print(f"25th Percentile: {np.percentile(scores, 25):.2f}")
print(f"75th Percentile: {np.percentile(scores, 75):.2f}")
print("_________________________________\n")

# Filter and display students scoring above the overall mean in one line
above_mean = student_df[student_df['Final_Score'] > np.mean(scores)]
print(f"Students with a Final Score above the overall mean ({np.mean(scores):.2f}) (Count: {len(above_mean)}):")
display(above_mean[['Student_ID', 'Name', 'Department', 'Final_Score']].head())

--- Final_Score Statistics ---
Mean: 70.70
Median: 70.95
Std Dev: 13.96
25th Percentile: 60.45
75th Percentile: 82.28
_________________________________

Students with a Final Score above the overall mean (70.70) (Count: 42):

  Student_ID         Name        Department  Final_Score
0    STU1001  Rahul Varma  Computer Science         82.7
4    STU1005    Asha Nair      Data Science         81.9
6    STU1007  Akhil Varma       Electronics         77.0
7    STU1008  Akhil Varma  Computer Science         79.2
8    STU1009   Diya Menon      Data Science         83.0

In [74]:
# Q16

student_df = pd.read_csv('/content/student_performance.csv')
student_df['Department'] = student_df['Department'].astype(str).str.strip().str.title()


# 1. Create Average_Score
score_cols = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
student_df['Average_Score'] = student_df[score_cols].mean(axis=1)

# 2. Create Pass_Status
student_df['Pass_Status'] = np.where(student_df['Average_Score'] >= 50, 'Pass', 'Fail')

# Display preview
display(student_df[['Name', 'Average_Score', 'Pass_Status']].head())

# 1. Top 5 students based on Average_Score
top_5 = student_df.sort_values(by='Average_Score', ascending=False).head(5)
print("\n1. Top 5 Students by Average Score:\n")
display(top_5[['Student_ID', 'Name', 'Department', 'Average_Score']])
print('\n_________________________________________\n')
# 2. Department with the highest average score (using Final_Score)
dept_avg_scores = student_df.groupby('Department')['Final_Score'].mean()
best_dept = dept_avg_scores.idxmax()
print(f"\n2. Department with the highest average score: {best_dept} ({dept_avg_scores.max():.2f})")
print('\n_________________________________________\n')
# 3. Calculate average attendance by department
dept_attendance = student_df.groupby('Department')['Attendance'].mean().reset_index()
print("\n3. Average Attendance by Department:")
display(dept_attendance)
print('\n_________________________________________\n')
# 4. Total number of students who passed and failed
pass_fail_counts = student_df['Pass_Status'].value_counts()
print("\n4. Pass/Fail Counts:")
print(pass_fail_counts)

print('\n_________________________________________\n')
# Ensure Pass and Fail columns are represented numerically for aggregation
student_df['Pass_Count'] = (student_df['Pass_Status'] == 'Pass').astype(int)
student_df['Fail_Count'] = (student_df['Pass_Status'] == 'Fail').astype(int)

# Group by Department and aggregate the specified metrics
dept_summary_df = student_df.groupby('Department').agg(
    Total_Students=('Student_ID', 'count'),
    Average_Score=('Average_Score', 'mean'),
    Average_Attendance=('Attendance', 'mean'),
    Pass_Count=('Pass_Count', 'sum'),
    Fail_Count=('Fail_Count', 'sum')
).reset_index()


# Display the final summary DataFrame
print("Summary Dataframe")
display(dept_summary_df)

             Name  Average_Score Pass_Status
0     Rahul Varma         83.575        Pass
1    Kiran Pillai         65.200        Pass
2  Fathima Joseph         73.400        Pass
3    Rahul Sharma         54.475        Pass
4       Asha Nair         83.275        Pass

1. Top 5 Students by Average Score:

   Student_ID          Name        Department  Average_Score
10    STU1011      Diya Das      Data Science         95.625
61    STU1062  Kiran Pillai  Computer Science         95.200
48    STU1049   Asha Sharma      Data Science         92.800
8     STU1009    Diya Menon      Data Science         92.125
16    STU1017  Rahul Thomas      Data Science         89.350

_________________________________________


2. Department with the highest average score: Electronics (72.85)

_________________________________________


3. Average Attendance by Department:

         Department  Attendance
0          Commerce   77.437500
1  Computer Science   83.127586
2      Data Science   81.892593
3       Electronics   80.576923

_________________________________________


4. Pass/Fail Counts:
Pass_Status
Pass    70
Fail    10
Name: count, dtype: int64

_________________________________________

Summary Dataframe

,Department,Total_Students,Average_Score,Average_Attendance,Pass_Count,Fail_Count
0,Commerce,8,68.793750,77.437500,8,0
1,Computer Science,30,69.830278,83.127586,24,6
2,Data Science,29,70.038793,81.892593,25,4
3,Electronics,13,74.063462,80.576923,13,0

In [91]:
# Q17
import numpy as np
import pandas as pd

# --- SECTION A: Data Preparation ---


# 1. Load the CSV file
sales_df = pd.read_csv('/content/sales.csv')

# 2. Convert Order_Date to datetime handling different formats
sales_df['Order_Date'] = pd.to_datetime(sales_df['Order_Date'], format='mixed', dayfirst=True)

# Clean numeric columns (remove potential currency symbols, commas, or whitespace and convert to float)
numeric_cols = ['Sales', 'Quantity', 'Discount', 'Profit']
for col in numeric_cols:
    if col in sales_df.columns:
        sales_df[col] = sales_df[col].astype(str).str.replace('$', '').str.replace(',', '').str.strip()
        sales_df[col] = pd.to_numeric(sales_df[col], errors='coerce')

# 3. Check and handle missing values
print("Missing values count before cleaning:")
print(sales_df.isnull().sum())

# Fill any missing numerical variables with their mean, and strings with 'Unknown'
for col in numeric_cols:
    sales_df[col] = sales_df[col].fillna(sales_df[col].mean())

string_cols = ['Product', 'Category', 'Region']
for col in string_cols:
    if col in sales_df.columns:
        sales_df[col] = sales_df[col].fillna('Unknown').astype(str).str.strip().str.title()

print("\nData preparation complete. Dimensions of dataset:", sales_df.shape)
display(sales_df.head())


# --- SECTION B: Sales Analysis ---
print("\n___________________________________\n")
# 1. Total sales and profit
total_sales = sales_df['Sales'].sum()
total_profit = sales_df['Profit'].sum()
print(f"1. Total Sales: ${total_sales:,.2f}")
print(f"2. Total Profit: ${total_profit:,.2f}")

# 2. Average sales
avg_sales = sales_df['Sales'].mean()
print(f"3. Average Sales per Order: ${avg_sales:,.2f}")

# 3. Top 5 products based on sales
top_products = sales_df.groupby('Product')['Sales'].sum().reset_index()
top_5_products = top_products.sort_values(by='Sales', ascending=False).head(5)
print("\n4. Top 5 Products by Sales:")
display(top_5_products)

# 4. Region generating the highest sales
region_sales = sales_df.groupby('Region')['Sales'].sum()
best_region = region_sales.idxmax()
print(f"\n5. Region generating the highest sales: {best_region} (${region_sales.max():,.2f})")

Missing values count before cleaning:
Order_ID      0
Order_Date    0
Product       0
Category      0
Region        1
Sales         0
Quantity      1
Discount      1
Profit        1
dtype: int64

Data preparation complete. Dimensions of dataset: (180, 9)

,Order_ID,Order_Date,Product,Category,Region,Sales,Quantity,Discount,Profit
0,ORD5001,2026-06-10,Office Chair,Furniture,East,142.10,1.0,0.02,12.78
1,ORD5002,2026-04-25,Usb Hub,Accessories,North,51.52,2.0,0.08,4.57
2,ORD5003,2026-03-07,Monitor,Computers,West,648.00,4.0,0.10,86.32
3,ORD5004,2026-03-19,Office Chair,Furniture,North,290.00,2.0,0.00,47.77
4,ORD5005,2026-01-25,Tablet,Computers,North,304.00,1.0,0.05,23.43

___________________________________

1. Total Sales: $94,400.44
2. Total Profit: $15,245.17
3. Average Sales per Order: $524.45

4. Top 5 Products by Sales:

      Product    Sales
4      Laptop  33995.0
7     Printer  13719.3
8      Tablet  10291.2
5     Monitor   9508.9
2  Headphones   5999.5

5. Region generating the highest sales: West ($37,314.18)